### ISSUE TITLE
Example Vixen.toml is Missing

### ISSUE THREAD

**Issue by notwedtm** [rpcpool/yellowstone-vixen#33]
The documentation makes reference to an example configuration file but that file is a 404: 
![image](https://github.com/user-attachments/assets/a5c08fae-1c20-4d24-aca9-72d3f0ee1523)

**Comment by 808putnam** [comment]
Went back in the commits to find a version to drop in. Here's what I found:
Vixen.toml:
[yellowstone]
# endpoint of the dragonmouth stream
endpoint = "https://index.rpcpool.com"
# x-token of the dragonmouth stream
x-token = "d19dadc5-f7bf-4dc6-bf71-b28d052baee6"
# dragonmouth connect timeout in seconds
timeout = 60
# #Prometheus metrics config, uncomment this while using prometheus
[metrics]
# # endpoint of the metrics stream (metrics data is pushed to this endpoint and consumed by prometheus)
endpoint = "http://localhost:3030"
# # job name of the metrics stream
job = "example"
# # username of the metrics stream
username = "foo"
# # password of the metrics stream
password = "bar"
# # metrics export interval in seconds
export-interval = 60
